if (!window.quizSets) window.quizSets = [];
window.quizSets[4] = {
    title: "対義語（その2）",
    questions: [
        { q1: "31. 大多数の人が彼の意見に（　）した。", ans1: "賛成", q2: "31. せっかくの案に（　）された。", ans2: "反対", type: "antonym", choices: ["賛成", "反対", "掃除機", "投げる", "固い", "砂漠"], render: commonRender },
        { q1: "32. 幼いころから（　）に親しんだ。", ans1: "自然", q2: "32. 農業用として作られた（　）の池。", ans2: "人工", type: "antonym", choices: ["自然", "人工", "電球", "喋る", "軽い", "倉庫"], render: commonRender },
        { q1: "33. 駅に（　）した後、電車で目的地に向かう。", ans1: "集合", q2: "33. 遠足は現地で（　）の予定だ。", ans2: "解散", type: "antonym", choices: ["集合", "解散", "財布", "盗む", "重い", "線路"], render: commonRender },
        { q1: "34. 会って話すことで（　）誤解が解けた。", ans1: "直接", q2: "34. 本人ではなく、友だちから（　）的に聞いた話。", ans2: "間接", type: "antonym", choices: ["直接", "間接", "看板", "飾る", "柔い", "踏切"], render: commonRender },
        { q1: "35. 解決に向かって一歩（　）する。", ans1: "前進", q2: "35. 時には、（　）する勇気も必要だ。", ans2: "後退", type: "antonym", choices: ["前進", "後退", "帽子", "被る", "強い", "標高"], render: commonRender },
        { q1: "36. 多くの人命が失われる（　）。", ans1: "戦争", q2: "36. 誰しもが（　）な世の中を願っている。", ans2: "平和", type: "antonym", choices: ["戦争", "平和", "眼鏡", "壊す", "弱い", "国境"], render: commonRender },
        { q1: "37. 重要な議題はクラス（　）で話し合うべきだ。", ans1: "全体", q2: "37. 桃は指でおすとその（　）が変色する。", ans2: "部分", type: "antonym", choices: ["全体", "部分", "石鹸", "練る", "鋭い", "議長"], render: commonRender },
        { q1: "38. 選手が（　）し、開会式が始まった。", ans1: "入場", q2: "38. 危険な行為で選手が（　）になる。", ans2: "退場", type: "antonym", choices: ["入場", "退場", "風船", "割る", "鈍い", "審判"], render: commonRender },
        { q1: "39. 閉店セールで家具を（　）で手に入れた。", ans1: "安価", q2: "39. 一冊、千円もする（　）なノートを買った。", ans2: "高価", type: "antonym", choices: ["安価", "高価", "毛布", "畳む", "荒い", "店主"], render: commonRender },
        { q1: "40. 合図とともにテストを（　）める。", ans1: "開始", q2: "40. 試合が（　）するまで油断は禁物だ。", ans2: "終了", type: "antonym", choices: ["開始", "終了", "鋏", "切る", "細かい", "監督"], render: commonRender },
        { q1: "41. （　）な立ち居振るまいに見とれる。", ans1: "上品", q2: "41. 汚い食べ方をして（　）だとしかられる。", ans2: "下品", type: "antonym", choices: ["上品", "下品", "絵画", "描く", "太い", "礼儀"], render: commonRender },
        { q1: "42. （　）な組織に一人で立ち向かう。", ans1: "強大", q2: "42. （　）なチームが努力して実力をつけていく。", ans2: "弱小", type: "antonym", choices: ["強大", "弱小", "地図", "見る", "細い", "団結"], render: commonRender },
        { q1: "43. この着物はなかなかの（　）な品だ。", ans1: "上等", q2: "43. （　）な生き物は本能に従って生きている。", ans2: "下等", type: "antonym", choices: ["上等", "下等", "電池", "替える", "深い", "品質"], render: commonRender },
        { q1: "44. 『羅生門』は芥川龍之介の（　）の作品だ。", ans1: "初期", q2: "44. 徳川慶喜は江戸（　）の将軍だ。", ans2: "末期", type: "antonym", choices: ["初期", "末期", "辞書", "引く", "浅い", "著者"], render: commonRender },
        { q1: "45. 母がたおれ、緊急（　）した。", ans1: "入院", q2: "45. 治療がうまく進み、無事（　）できた。", ans2: "退院", type: "antonym", choices: ["入院", "退院", "枕", "投げる", "多い", "医者"], render: commonRender },
        { q1: "46. 自分だけが（　）になるような決まりはずるい。", ans1: "有利", q2: "46. （　）を承知で勝負に出る。", ans2: "不利", type: "antonym", choices: ["有利", "不利", "電柱", "登る", "少ない", "平等"], render: commonRender },
        { q1: "47. はしを使う（　）の作法。", ans1: "和式", q2: "47. ナイフやフォークを使う（　）の作法。", ans2: "洋式", type: "antonym", choices: ["和式", "洋式", "花瓶", "割る", "固い", "食事"], render: commonRender },
        { q1: "48. 新しい発見によって、科学の技術が（　）する。", ans1: "進歩", q2: "48. 研究が進まず、むしろ（　）したように感じる。", ans2: "退歩", type: "antonym", choices: ["進歩", "退歩", "楽器", "弾く", "脆い", "博士"], render: commonRender },
        { q1: "49. 試合の（　）をみんなで祝う。", ans1: "勝利", q2: "49. ほんのわずかなミスで、（　）を喫する。", ans2: "敗北", type: "antonym", choices: ["勝利", "敗北", "手袋", "嵌める", "重い", "優勝"], render: commonRender },
        { q1: "50. 料理を作るのは（　）で、失敗ばかりしている。", ans1: "苦手", q2: "50. わたしの最も（　）な科目は算数です。", ans2: "得意", type: "antonym", choices: ["苦手", "得意", "看板", "剥がす", "軽い", "献立"], render: commonRender },
        { q1: "51. 授業を（　）することは大切だ。", ans1: "予習", q2: "51. 来週の学習内容を（　）しておく。", ans2: "復習", type: "antonym", choices: ["予習", "復習", "消しゴム", "拾う", "速い", "教科書"], render: commonRender },
        { q1: "52. （　）に相談してから実行する。", ans1: "事前", q2: "52. 遊びに行ったことを、母親に（　）報告する。", ans2: "事後", type: "antonym", choices: ["事前", "事後", "電話", "掛ける", "遅い", "計画"], render: commonRender },
        { q1: "53. アゲハの（　）がみかんの葉を食べる。", ans1: "幼虫", q2: "53. 羽化して（　）となる。", ans2: "成虫", type: "antonym", choices: ["幼虫", "成虫", "金槌", "叩く", "長い", "観察"], render: commonRender },
        { q1: "54. 漢方を用いた（　）の医学。", ans1: "東洋", q2: "54. （　）では自然を支配するという意識が強い。", ans2: "西洋", type: "antonym", choices: ["東洋", "西洋", "毛布", "被る", "短い", "病院"], render: commonRender },
        { q1: "55. 主将を列の（　）にして、グラウンドに入場する。", ans1: "先頭", q2: "55. 手紙の（　）にそえる言葉を考える。", ans2: "末尾", type: "antonym", choices: ["先頭", "末尾", "切手", "貼る", "太い", "行進"], render: commonRender },
        { q1: "56. 希少品は（　）で取り引きされる。", ans1: "高値", q2: "56. 思いがけず（　）で落札できて得をした。", ans2: "安値", type: "antonym", choices: ["高値", "安値", "封筒", "開ける", "細い", "競売"], render: commonRender },
        { q1: "57. あのデパートは銀座に（　）がある。", ans1: "本店", q2: "57. 全国に（　）がある和菓子屋さん。", ans2: "支店", type: "antonym", choices: ["本店", "支店", "暖簾", "潜る", "厚い", "開店"], render: commonRender },
        { q1: "58. （　）な人材を失うことはさけたい。", ans1: "有用", q2: "58. わたしたち親友の間で遠慮は（　）です。", ans2: "無用", type: "antonym", choices: ["有用", "無用", "名刺", "配る", "薄い", "雇用"], render: commonRender },
        { q1: "59. わたしの（　）は武士だったらしい。", ans1: "先祖", q2: "59. わたしたち（　）のために地球環境は守るべきだ。", ans2: "子孫", type: "antonym", choices: ["先祖", "子孫", "家系図", "書く", "鋭い", "墓参り"], render: commonRender },
        { q1: "60. 水温の低い海流を（　）と呼ぶ。", ans1: "寒流", q2: "60. 黒潮は日本近海を流れる（　）として有名だ。", ans2: "暖流", type: "antonym", choices: ["寒流", "暖流", "浮輪", "膨らます", "鈍い", "漁業"], render: commonRender },
        { q1: "61. がんばって働いたので、今月は（　）が多い。", ans1: "収入", q2: "61. 欲しい物を買っていると（　）が多くなる。", ans2: "支出", type: "antonym", choices: ["収入", "支出", "通帳", "記帳する", "甘い", "貯金"], render: commonRender },
        { q1: "62. 日本は車や電化製品を海外に（　）している。", ans1: "輸出", q2: "62. 日本は食べ物を海外から（　）している。", ans2: "輸入", type: "antonym", choices: ["輸出", "輸入", "コンテナ", "運ぶ", "苦い", "貿易"], render: commonRender }
    ]
};
